<?php
/**
 * Copyright © Vaimo Group. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */

$viewModel = $block->getViewModel();
$_product = $block->getProduct();
$bundlePrice = '';
if ($_product->getTypeId() == 'bundle') {
    $bundlePrice = $_product->getPriceInfo()->getPrice('regular_price')->getMinimalPrice()->getValue();
}
?>

<?php if ($block->escapeHtmlAttr($_product->getTypeId() !== 'giftcard') && $viewModel->isEnabledForLocation()): ?>

<div data-bind="scope: 'calculator-holder'" class="calculator-holder" >

    <button id="svea-calc-btn" type="button" class="action primary calc-btn" data-trigger="" data-bind="afterRender: replacePriceAmount, attr: {'data-trigger': state.triggerEvent()}">
        <span><?=  $escaper->escapeHtml(__('Part Payment Calculator'))?></span>
        <span class="svea-img-holder">
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 181.9 67.2" fill="#fff" class="site-logo-svg">
                <path class="site-logo-svg__text-path" d="M29 18.6H16.6c-4.5 0-5-2.2-5-4 0-3.5 1.8-5 6.3-5h24V0H16.5C5.3 0 0 4.6 0 14.6c0 9.3 5 13.7 15.7 13.7h11.1c4.3 0 5.8 1 5.8 4.3 0 2.7-1 4.1-6.4 4.1H1.8v9.7h25.9c11.2 0 16.5-4.5 16.5-14.2S39.8 18.6 29 18.6zM81.9 0L68.8 31.8 55.9 0H43.3l20.3 46.4h10.8L93.8 0zm31.3 9.5h16.3V0H113C98.1 0 91.1 7.6 91.1 24c0 8.5 2.4 14.4 7.2 18.3 4.8 3.8 9.4 4.1 14.5 4.1h16.7v-9.6h-16.3c-6.7 0-9.4-2.5-9.7-9.1h26v-9.5h-25.9c.6-5.9 3.7-8.7 9.6-8.7zM151.1 0l-19.6 46.4h11.9l4-10.6h18.1l4.1 10.6H182L162.2 0h-11.1zm-.1 26l5.2-13.8 5.4 13.8H151z"></path>
                <path class="site-logo-svg__underline-path" fill="#00aece" d="M3.7 55.2h176c1.2 0 2.2 1 2.2 2.2V65c0 1.2-1 2.2-2.2 2.2H3.7c-1.2 0-2.2-1-2.2-2.2v-7.6c0-1.2 1-2.2 2.2-2.2z"></path>
            </svg>
        </span>
    </button>

    <div id="svea-calc-msg-info" class="calculator-message-info">
        <span><?= $escaper->escapeHtml(__('Part payment is not available at this purchase price')) ?></span>
    </div>

    <div data-bind="mageInit: {
    'Magento_Ui/js/modal/modal':{
        'type': 'popup',
        'trigger': '[data-trigger=trigger-open]',
        'modalClass': 'svea-modal',
        'responsive': true,
        'buttons': [{
            text: jQuery.mage.__('Close'),
            class: 'action'
        }]
    }}">
        <div class="content">
            <!-- ko template:getTemplate() --><!-- /ko -->
            <div class="svea-script-holder">
                <?= $viewModel->getCalculatorScript($block) . '</script>' ?>
            </div>
        </div>
    </div>

</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "calculator-holder": {
                        "component": "Svea_SveaPayment/js/view/calculator/pdp/calculator-handle-pdp",
                        "productPrice": "<?= $block->escapeHtmlAttr($_product->getFinalPrice()); ?>",
                        "productType": "<?= $block->escapeHtmlAttr($_product->getTypeId()); ?>",
                        "bundlePrice":"<?= $bundlePrice ?>"
                    }
                }
            }
        }
    }
</script>

<?php endif; ?>
