<?php
/**
 * Copyright © Vaimo Group. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */

$viewModel = $block->getViewModel();
$_product = $block->getProduct();
$bundlePrice = '';
if ($_product->getTypeId() == 'bundle') {
    $bundlePrice = $_product->getPriceInfo()->getPrice('regular_price')->getMinimalPrice()->getValue();
}
?>

<?php if ($block->escapeHtmlAttr($_product->getTypeId() !== 'giftcard') && $viewModel->isEnabledForLocation()): ?>

<div data-bind="scope: 'calculator-holder'" class="calculator-holder" >

    <!-- ko template:getTemplate() --><!-- /ko -->
    <div class="svea-script-holder">
        <?= $viewModel->getCalculatorScript($block) . '</script>' ?>
    </div>

    <div id="svea-calc-msg-info" class="calculator-message-info">
        <span><?= $escaper->escapeHtml(__('Part payment is not available at this purchase price')) ?></span>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "calculator-holder": {
                        "component": "Svea_SveaPayment/js/view/calculator/pdp/calculator-handle-pdp",
                        "productPrice": "<?= $block->escapeHtmlAttr($_product->getPriceInfo()->getPrice('final_price')->getAmount() ) ?>",
                        "productType": "<?= $block->escapeHtmlAttr($_product->getTypeId()); ?>",
                        "bundlePrice":"<?= $bundlePrice ?>"
                    }
                }
            }
        }
    }
</script>

<?php endif; ?>
