<?php
/**
 * Copyright © Vaimo Group. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->isEnabledForLocation()) :?>

    <div data-bind="scope: 'calculator-holder'" class="calculator-holder">

        <div id="svea-pp-calculator-container">
        <!-- ko template:getTemplate() --><!-- /ko -->
            <div class="svea-script-holder">
                <?= $viewModel->getCalculatorScript($block) . '</script>' ?>   
            </div>

            <div id="svea-calc-msg-info" class="calculator-message-info">
                <span><?= $escaper->escapeHtml(__('Part payment is not available at this purchase price')) ?></span>
            </div>
        </div>

    </div>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "calculator-holder": {
                            "component": "Svea_SveaPayment/js/view/calculator/calculator-handle"
                        }
                    }
                }
            }
        }
    </script>
<?php endif;?>
