<?php
    $order = $block->getOrder();
    $memo = $block->getCreditMemo();
    $display = ['display' => \Magento\Framework\Currency::NO_SYMBOL];
?>

<tr>
    <td class="label"><?= /* @escapeNotVerified */ \__('Invoicing Fee Tax') ?><div id="svea_handling_fee_tax"></div></td>
    <td>
        <input type="text"
               name="creditmemo[svea_handling_fee_tax]"
               value="<?= $order->getBaseCurrency()->format((float)$memo->getSveaHandlingFeeTax(), $display, false) ?>"
               class="input-text admin__control-text not-negative-amount"
               id="svea_handling_fee_tax" />
    </td>
</tr>
